### ISSUE TITLE
"failed to parse module" due to "Unexpected token `@`"

### ISSUE THREAD

**Issue by rthreei** [Brooooooklyn/swc-node#210]
```
error: Unexpected token `@`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier
  --> my.ts:31:1
   |
31 | @injectable()
 FAIL  my.test.ts
  ● Test suite failed to run

    GenericFailure: failed to process js file

    Caused by:
        failed to parse module

      at Compiler.transformSync (node_modules/@swc/core/index.js:116:25)
      at Object.transformSync (node_modules/@swc/core/index.js:196:21)
      at Object.transformJest (node_modules/@swc-node/core/index.ts:59:10)
      at Object.process (node_modules/@swc-node/jest/index.ts:8:14)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

injectable is from [InversifyJS](https://github.com/inversify/InversifyJS#step-2-declare-dependencies-using-the-injectable--inject-decorators)

**Comment by Brooooooklyn** [comment]
set `experimentalDecorators: true` and `emitDecoratorMetadata: true` in `jest.config`
```js
  transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc-node/jest',

      // configuration
      {
        dynamicImport: true,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
      },
    ],
  },
```

**Comment by rthreei** [comment]
Thanks, made progress with that, but now seeing this error:
```
thread '<unnamed>' panicked at 'not implemented: decorators on methods with computed key', ecmascript/transforms/ FAIL  my.test.ts
  ● Test suite failed to run

    GenericFailure: not implemented: decorators on methods with computed key

      at Compiler.transformSync (../node_modules/@swc/core/index.js:116:25)
      at Object.transformSync (../node_modules/@swc/core/index.js:196:21)
      at Object.transformJest (../node_modules/@swc-node/core/index.ts:59:10)
      at Object.process (../node_modules/@swc-node/jest/index.ts:8:14)
      at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:607:25)
```

**Comment by Brooooooklyn** [comment]
Oh, could you please provide a minimal code snippets to reproduce the error?

**Comment by rthreei** [comment]
https://github.com/Brooooooklyn/swc-node/compare/master...rthreei:repro/issue-210?expand=1

**Comment by Brooooooklyn** [comment]
@kdy1 add you as collaborator, feel free to transfer this issue into swc

**Comment by kdy1** [comment]
@Brooooooklyn Thanks!

**Comment by Brooooooklyn** [comment]
@kdy1  https://github.com/Brooooooklyn/swc-node/invitations invitation link

**Comment by rthreei** [comment]
Hey, did this get transferred?

**Comment by kdy1** [comment]
Not yet because github does not show swc repo in transfer list,
![image](https://user-images.githubusercontent.com/29931815/101906689-b5091200-3bfc-11eb-98e8-a381bd85fb20.png)

but I'm aware of this issue.
