### ISSUE TITLE
.toMatchInlineSnapshot() fails

### ISSUE THREAD

**Issue by JSanchezIO** [Brooooooklyn/swc-node#367]
**Source Code**
```
test('given no DIContainerContext.Provider then an error is thrown', () => {
    const { result } = renderHook(() => useDIContainer());

    expect(result.error?.message).toMatchInlineSnapshot();
  });
```

**Output**
```
Test suite failed to run

    Jest: Couldn't locate all inline snapshots.

      at Object.parse (node_modules/jest-snapshot/build/InlineSnapshots.js:267:11)
      at Object.parse (node_modules/prettier/index.js:13625:19)
      at coreFormat (node_modules/prettier/index.js:14899:14)
      at format (node_modules/prettier/index.js:15131:14)
      at node_modules/prettier/index.js:57542:12
      at Object.format (node_modules/prettier/index.js:57562:12)
```

**Comment by JSanchezIO** [comment]
Was this related to, https://swc.rs/blog/2021/04/20/swc-1.2.54#sourcemaps-1581?

**Comment by Brooooooklyn** [comment]
@JSanchezIO I can not reproduce in https://github.com/Brooooooklyn/swc-node/issues/367, could you please provide your jest config?

**Comment by JSanchezIO** [comment]
It's working locally for me now.

**Comment by JSanchezIO** [comment]
Just for awareness, this was the jest config:

```
module.exports = {
  setupFilesAfterEnv: ['./jest.setup.ts'],
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: ['<rootDir>/e2e/', '/node_modules/', '/.stryker-tmp/'],
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc-node/jest'],
  },
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
};
```

**Comment by Gervwyk** [comment]
Also experiencing this issue on `"jest": "27.3.1",` and `"@swc/jest": "0.2.5",`
