### ISSUE TITLE
typescript metadata work error(nestjs)

### ISSUE THREAD

**Issue by pincman** [Brooooooklyn/swc-node#502]
.swcrc
```json
{
    "jsc": {
        "loose": true,
        "target": "es2020",
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        }
    },
    "module": {
        "type": "commonjs",
        "strict": true,
        "strictMode": true,
        "lazy": true,
        "noInterop": true
    }
}
```
![image](https://user-images.githubusercontent.com/74093067/123497644-40119d00-d661-11eb-9926-b4c481871f0f.png)

**Comment by Brooooooklyn** [comment]
Could you provide a minimal code snippet to reproduce this issue?

**Comment by pincman** [comment]
@Brooooooklyn 
My code
```typescript
@Delete()
    @SerializeOptions({ groups: ['category-list'] })
    async destroyMulti(
        @Query()
        { page, limit }: QueryCategoryDto,
        @Body()
        { trash, categories }: DeleteCategoryMultiDto,
    ) {
        return this.categoryService.deletePaginate(
            categories,
            {
                page,
                limit,
            },
            {},
            trash,
        );
    }
```
and
if running by `@swc/register` every thing is work fine
```typescript
const runner = nodemon({
        script: 'src/main.ts',
        ext: 'js,json,ts',
        watch: ['src'],
        ignore: ['.git', 'node_modules', 'dist', 'scripts'],
        execMap: {
            ts: 'node -r @swc/register -r module-alias/register',
        },
        env: {
            NODE_ENV: environment(),
        },
        cwd: path.resolve(__dirname, '..', '..'),
        spawn: true,
    });
    runner.once('start', () => {
        console.log();
        console.log('Server has started:');
        if (urls.length > 0) {
            console.log(`- Local: ${chalk.green.underline(urls[0])}`);
        }
        if (urls.length > 1) {
            console.log(`- Network: ${chalk.green.underline(urls[1])}`);
        }
    });
    runner.on('restart', () => {
        console.log();
        console.log(chalk.yellow('Server is in restarting...'));
    });
```
![image](https://user-images.githubusercontent.com/74093067/123633836-4a43bf00-d84c-11eb-96d0-533e3af11554.png)
but when change to `@swc-node/register`,will get this error
```typescript
 execMap: {
            ts: 'node -r @swc-node/register -r module-alias/register',
        },
```
![image](https://user-images.githubusercontent.com/74093067/123634095-9858c280-d84c-11eb-9c6a-7e0bf234a6cb.png)

I think the reason that is `@swc-node/register` not read the config file `.swcrc`,
```json
{
    "sourceMaps": false,
    "jsc": {
        "loose": true,
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        },
        "target": "es2020",
        "externalHelpers": false
    },
    "module": {
        "type": "commonjs"
    }
}

```
how to read it for this project `@swc-node`?

**Comment by TechQuery** [comment]
@Brooooooklyn I don't know how to configuration SWC in the right way for legacy **Decorator metadata** too:

## `.swcrc`

```json
{
    "module": {
        "type": "commonjs"
    },
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "decorators": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true
        }
    }
}
```

## Error

```text
cross-env SWCRC=true  node -r @swc-node/register --watch source/

D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\routing-controllers\cjs\metadata\ParamMetadata.js:49
            this.isTargetObject = this.targetType instanceof Function || this.targetType.toLowerCase() === 'object';  
                                                                                         ^

TypeError: this.targetType.toLowerCase is not a function
    at new ParamMetadata (D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata\ParamMetadata.ts:138:84)
    at D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:121:25
    at Array.map (<anonymous>)
    at MetadataBuilder.createParams (D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:121:8)
    at D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:103:32
    at Array.forEach (<anonymous>)
    at MetadataBuilder.createActions (D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:100:10)
    at D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:83:33
    at Array.map (<anonymous>)
    at MetadataBuilder.createControllers (D:\Work\Community\KaiYuanShe\OpenHackathon-service\node_modules\.pnpm\routing-controllers@0.10.4_class-transformer@0.5.1_class-validator@0.14.1\node_modules\src\metadata-builder\MetadataBuilder.ts:80:24)

Node.js v20.15.1
Failed running 'source/'
```
